column_count: 38
columns:
- lg_code
- machiaza_id
- machiaza_type
- pref
- pref_kana
- pref_roma
- county
- county_kana
- county_roma
- city
- city_kana
- city_roma
- ward
- ward_kana
- ward_roma
- oaza_cho
- oaza_cho_kana
- oaza_cho_roma
- chome
- chome_kana
- chome_number
- koaza
- koaza_kana
- koaza_roma
- machiaza_dist
- rsdt_addr_flg
- rsdt_addr_mtd_code
- oaza_cho_aka_flg
- koaza_aka_code
- oaza_cho_gsi_uncmn
- koaza_gsi_uncmn
- status_flg
- wake_num_flg
- efct_date
- ablt_date
- src_code
- post_code
- remarks
container: zip
delimiter: ','
encoding: utf-8
fingerprint: a192e90e2ee45ad95bd8f28a2c06a57a01ea9aa9dba906e413dbc25b330d1269
has_header: true
members:
- mt_town_all.csv
sheet_names: []
