column_count: 29
columns:
- KEY_CODE
- PREF
- CITY
- S_AREA
- PREF_NAME
- CITY_NAME
- S_NAME
- KIGO_E
- HCODE
- AREA
- PERIMETER
- R2KAxx
- R2KAxx_ID
- KIHON1
- DUMMY1
- KIHON2
- KEYCODE1
- KEYCODE2
- AREA_MAX_F
- KIGO_D
- N_KEN
- N_CITY
- KIGO_I
- KBSUM
- JINKO
- SETAI
- X_CODE
- Y_CODE
- KCODE1
container: zip
delimiter: ''
encoding: cp932
fingerprint: 7fa522e5f155846be56b4f46f0c1d047d12f69278c397335288140db554674e0
has_header: true
members: []
sheet_names: []
